#!/bin/bash
set -e  # Exit on error

sudo apt update && \
sudo apt install -y pciutils nano htop nvtop zstd && \
curl https://ollama.ai/install.sh | sh && \
sudo mkdir -p /etc/systemd/system/ollama.service.d && \
sudo sh -c 'cat > /etc/systemd/system/ollama.service.d/environment.conf << '\''EOF'\''
[Service]
Environment="OLLAMA_HOST=0.0.0.0:11434"
Environment="OLLAMA_KEEP_ALIVE=-1"
Environment="OLLAMA_NUM_CTX=131072"
Environment="OLLAMA_NUM_GPU=-1"
Environment="OLLAMA_GPU_MEMORY_FRACTION=0.9"
Environment="OLLAMA_TENSOR_PARALLEL=true"
EOF'
sudo systemctl daemon-reload && \
sudo systemctl restart ollama && \
sleep 3 && \
##ollama pull gpt-oss:120b && \
ollama pull gpt-oss:20b && \
ollama pull devstral-small-2:24b-instruct-2512-q8_0 && \
ollama pull glm-4.7-flash:q8_0 && \
ollama pull qwen3-coder:30b-a3b-q8_0
