#!/bin/bash
set -e  # Exit on error

sudo apt update && \
sudo apt install -y pciutils nano htop nvtop zstd && \
curl https://ollama.ai/install.sh | sh && \
sudo mkdir -p /etc/systemd/system/ollama.service.d && \
sudo sh -c 'cat > /etc/systemd/system/ollama.service.d/environment.conf << '\''EOF'\''
[Service]
Environment="OLLAMA_HOST=0.0.0.0:11434"
Environment="OLLAMA_KEEP_ALIVE=-1"
Environment="OLLAMA_NUM_CTX=131072"
Environment="OLLAMA_NUM_GPU=-1"
Environment="OLLAMA_GPU_MEMORY_FRACTION=0.9"
Environment="OLLAMA_TENSOR_PARALLEL=true"
EOF'
sudo systemctl daemon-reload && \
sudo systemctl restart ollama && \
sleep 3 && \
ollama pull hf.co/unsloth/Qwen3.5-35B-A3B-GGUF:UD-Q4_K_XL
